### ISSUE TITLE
_async_get_candle_history() returned exception

### ISSUE THREAD

**Issue by vinceyap88** [adrianceding/binance-proxy#2]
Hi,
   I tried to use the latest binance-proxy and the recommended config with freqtrade 2022.5.1, but freqtrade fail to start with the following error:
freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair TLM/BUSD due to RequestTimeout. Message: binance GET http://127.0.0.1:8090/api/v3/klines?interval=1d&limit=1000&symbol=TLMBUSD&startTime=1655856000000". Retrying still for 4 times.
   Without connecting binance-proxy, it works successfully.

**Comment by abbaselmas** [comment]
i am getting the same error, but if you wait binance will respond and everything will be fine.
Just wait 👍🏼

**Comment by adrianceding** [comment]
> Hi, I tried to use the latest binance-proxy and the recommended config with freqtrade 2022.5.1, but freqtrade fail to start with the following error: freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair TLM/BUSD due to RequestTimeout. Message: binance GET http://127.0.0.1:8090/api/v3/klines?interval=1d&limit=1000&symbol=TLMBUSD&startTime=1655856000000". Retrying still for 4 times. Without connecting binance-proxy, it works successfully.

kline needs to rely on api data for initialization. And due to the **limit** and **wait the first websocket push data**, there may be a certain delay. About a few seconds.

So wait a while and it will be normal
